data_args:

  dataset: Preview # [CompleteUser1, Preview]
  accDuration: 600
  accStride: 600

  locDuration: 12 # samples
  locStride: 1 # samples

  path: /home/chris/SHL

  accSamplingRate: 0.1   # Period [seconds]
  gpsSamplingRate: 60
  samplingThreshold: 10

  interpolation: true
  interpolateThreshold: 3

  src_path: /home/chris/SHL/srcData

  majorityVoting: false
  majority: 0.5

  accBagSize: 3
  accBagStride: 600
  sync: Present # [ Past, Present, Future ]

train_args:

  pair_threshold: 60

  accBagSize: 3 # odd for Present
  accBagStride: 600
  accDuration: 600
  sync: Present # Past, Present, Future

  acc_augmentation: # ['Jittering','Permutation','TimeWarp','Rotation']

  acc_signals:
  - Acc_norm
  - Jerk
  use_spectrograms: true
  freq_interpolation: log # linear, log
  log_power: true
  specto_window: 10  #seconds
  specto_overlap: 9   #seconds
  specto_augment:   #[timeWarp, frequencyMask, timeMask, randomMask]
  - frequencyMask
  - timeMask
  acc_concat: Depth # [Depth, Frequency]
  acc_shape: 2D # [1D, 2D]
  acc_channel: Frequency # [Frequency, Time]

  gps_augmentation: true

  padding_threshold:
  mask: -10000000
  symmetric: false

  time_features:   # ['Distance','Velocity','Acceleration','Jerk','Bearing','BearingRate']
  - Velocity
  - Acceleration

  statistical_features: # [TotalMovability, Mean, Var]
  - TotalMovability
  - Mean
  - Var

  point_features: []

  valBatchSize: 32
  trainBatchSize: 32
  testBatchSize: 32

  test_user: 3

  val_percentage: 0.15  # used if stratify == concentrated
  randomize: true

  separate_MIL: false
  L: 256
  D: 256

  learning_rate: 0.0001

  epochs: 160
  accEpochs: 160
  locEpochs: 200

  transfer_learning_acc: train  # train, load, none
  transfer_learning_loc: none   # train, load, none
  finetuning: false
  fusion: MIL    # concat, MIL
  layer_norm: false

  transition_threshold: 120

  verbose: 1
  heads: 1

  train_bag_positions: same   # same, random, variable
  test_bag_positions: same   # same, random, variable
  train_position: all  # Hand, Torso, Bag, Hips, all
  test_position: all  # Hand, Torso, Bag, Hips, all
  multiple_test: true
  multiple_val: true
  multiple_train: true
  oversampling: false

  motorized: false

