data_args:

  dataset: Preview #[CompleteUser1, Preview]
  accDuration: 1200
  accStride: 1200

  locDuration: 12   #samples
  locStride: 1 #samples

  path: /home/chris/SHL

  accSamplingRate: 0.05 # Period [seconds]
  gpsSamplingRate: 60
  samplingThreshold: 10

  interpolation: true
  interpolateThreshold: 3

  src_path: /home/chris/SHL/srcData

  majority: 0.6

  accBagSize: 3
  accBagStride: 1200
  sync: Present # [ Past, Present, Future ]

train_args:

  pair_threshold: 60



  accBagSize: 3 # odd for Present
  accBagStride: 1200
  accDuration: 1200
  sync: Present # [ Past, Present, Future ]

  acc_augmentation:            #['Jittering','Permutation','TimeWarp','Rotation']

  acc_signals:
  - Acc_x
  - Acc_y
  - Acc_z
  - Acc_norm
  - Jerk

  use_spectrograms: true
  specto_window: 10  #seconds
  specto_overlap: 9.5 #seconds
  specto_augment: [frequencyMask, timeMask]  #[timeWarp, frequencyMask, timeMask, randomMask]
  acc_concat: Depth # [Depth, Frequency]
  acc_shape: 2D # [1D, 2D]
  acc_channel: Time # [Frequency, Time]

  gps_augmentation: true

  padding_threshold:
  mask: -10000000

  time_features:   #['Distance','Velocity','Acceleration','Jerk','Bearing','BearingRate']
  - Velocity
  - Acceleration

  statistical_features: #[TotalMovability, Mean, Var]
  - TotalMovability
  - Mean
  - Var

  point_features: []

  valBatchSize: 32
  trainBatchSize: 32
  testBatchSize: 32

  test_user: 2

  val_percentage: 0.15          # used if stratify == concentrated
  randomize: true

  separate_MIL: false

  learning_rate: 0.0001

  epochs: 80
  accEpochs: 160
  locEpochs: 200

  transfer_learning_acc: train #[train, load, none]
  transfer_learning_loc: none   #[train, load, none]

  transition_threshold: 120

  verbose: 1
  heads: 1

  random_position: true




